export const AZURE_PUBLIC_REGIONS = [
  "australiacentral",
  "australiacentral2",
  "australiaeast",
  "australiasoutheast",
  "austriaeast",
  "belgiumcentral",
  "brazilsouth",
  "brazilsoutheast",
  "canadacentral",
  "canadaeast",
  "centralindia",
  "centralus",
  "chilecentral",
  "denmarkeast",
  "eastasia",
  "eastus",
  "eastus2",
  "francecentral",
  "francesouth",
  "germanynorth",
  "germanywestcentral",
  "indonesiacentral",
  "israelcentral",
  "italynorth",
  "japaneast",
  "japanwest",
  "jioindiacentral",
  "jioindiawest",
  "koreacentral",
  "koreasouth",
  "malaysiawest",
  "mexicocentral",
  "newzealandnorth",
  "northcentralus",
  "northeurope",
  "norwayeast",
  "norwaywest",
  "polandcentral",
  "qatarcentral",
  "southafricanorth",
  "southafricawest",
  "southcentralus",
  "southindia",
  "southeastasia",
  "spaincentral",
  "swedencentral",
  "switzerlandnorth",
  "switzerlandwest",
  "uaecentral",
  "uaenorth",
  "uksouth",
  "ukwest",
  "westcentralus",
  "westeurope",
  "westindia",
  "westus",
  "westus2",
  "westus3",
] as const;

const AZURE_PUBLIC_REGION_SET = new Set<string>(AZURE_PUBLIC_REGIONS);

export function isAzurePublicRegion(value: string): boolean {
  return AZURE_PUBLIC_REGION_SET.has(value.trim().toLowerCase());
}
