import completeCatalog from "../../azure-complete-catalog-vscode.json";

export type SketchServiceType = string;
export type SketchParameterValue =
  | string
  | number
  | boolean
  | { [key: string]: SketchParameterValue }
  | SketchParameterValue[];

export interface SketchNode {
  id: string;
  serviceType: SketchServiceType;
  name: string;
  region: string;
  x: number;
  y: number;
  parameters?: Record<string, SketchParameterValue>;
}

export interface SketchConnection {
  id: string;
  source: string;
  target: string;
  bidirectional?: boolean;
}

export interface InfraSketch {
  version: 1;
  nodes: SketchNode[];
  connections: SketchConnection[];
}

export const SKETCH_SERVICES = Object.values(completeCatalog.services).map(
  (service) => ({
    type: service.serviceId,
    title: service.displayName,
    short: service.shortName ?? service.displayName.slice(0, 4).toUpperCase(),
    color: service.color ?? "#2563eb",
    category: service.category,
    description: service.description,
  }),
);

const SERVICE_TYPES = new Set(SKETCH_SERVICES.map((service) => service.type));

export function normalizeInfraSketch(input: unknown): InfraSketch {
  if (!input || typeof input !== "object") {
    throw new Error("Infrastructure sketch must be an object.");
  }
  const value = input as Record<string, unknown>;
  if (!Array.isArray(value.nodes) || !Array.isArray(value.connections)) {
    throw new Error("Infrastructure sketch requires nodes and connections.");
  }
  const nodes = value.nodes.map((item, index) => normalizeNode(item, index));
  const nodeIds = new Set(nodes.map((node) => node.id));
  if (nodeIds.size !== nodes.length) {
    throw new Error("Infrastructure sketch node IDs must be unique.");
  }
  const connections = value.connections.map((item, index) => {
    if (!item || typeof item !== "object") {
      throw new Error(`Connection ${index + 1} must be an object.`);
    }
    const entry = item as Record<string, unknown>;
    const source = String(entry.source ?? "");
    const target = String(entry.target ?? "");
    if (!nodeIds.has(source) || !nodeIds.has(target) || source === target) {
      throw new Error(`Connection ${index + 1} must link two different nodes.`);
    }
    return {
      id: cleanId(String(entry.id ?? `connection-${index + 1}`)),
      source,
      target,
      ...(entry.bidirectional === true ? { bidirectional: true } : {}),
    };
  });
  return { version: 1, nodes, connections };
}

export function generateTerraformFromSketch(
  sketch: InfraSketch,
  terraformVersion = ">= 1.5.0, < 2.0.0",
): string {
  const normalized = normalizeInfraSketch(sketch);
  if (normalized.nodes.length === 0) {
    throw new Error("Add at least one Azure service before generating Terraform.");
  }
  const context = createContext(normalized);
  const needsClientConfig = normalized.nodes.some((node) =>
    ["key_vault", "sql_server"].includes(node.serviceType),
  );
  const kubernetesCluster = normalized.nodes.find(
    (node) => node.serviceType === "kubernetes_service",
  );
  const needsKubernetesProvider =
    kubernetesCluster !== undefined &&
    normalized.nodes.some(
      (node) => node.serviceType === "kubernetes_namespace",
    );
  const generatedResourceGroup = context.resourceGroup
    ? []
    : [
        'resource "azurerm_resource_group" "sketch" {',
        '  name     = "rg-cloud-canvas"',
        `  location = ${JSON.stringify(normalized.nodes[0].region)}`,
        "  tags = {",
        '    managed_by = "terraform"',
        '    source     = "cloud-canvas"',
        "  }",
        "}",
        "",
      ];
  const clientConfig = needsClientConfig
    ? ['data "azurerm_client_config" "current" {}', ""]
    : [];
  const sections = normalized.nodes.map((node) =>
    renderNode(node, normalized, context),
  );
  const networkAssociations = renderNetworkAssociations(normalized, context);
  return [
    "# Generated by Azure IaC Guardrail: Cloud Canvas",
    "# Review names, network ranges, SKUs, and identity settings before deployment.",
    "",
    'terraform {',
    `  required_version = ${JSON.stringify(terraformVersion)}`,
    "",
    "  required_providers {",
    "    azurerm = {",
    '      source  = "hashicorp/azurerm"',
    '      version = "~> 4.0"',
    "    }",
    ...(needsKubernetesProvider
      ? [
          "    kubernetes = {",
          '      source  = "hashicorp/kubernetes"',
          '      version = "~> 2.0"',
          "    }",
        ]
      : []),
    "  }",
    "}",
    "",
    'provider "azurerm" {',
    "  features {}",
    "}",
    "",
    ...(needsKubernetesProvider
      ? kubernetesProvider(
          context.labels.get(kubernetesCluster.id) as string,
        )
      : []),
    ...generatedResourceGroup,
    ...clientConfig,
    ...sections,
    ...networkAssociations,
  ].join("\n");
}

function normalizeNode(input: unknown, index: number): SketchNode {
  if (!input || typeof input !== "object") {
    throw new Error(`Node ${index + 1} must be an object.`);
  }
  const value = input as Record<string, unknown>;
  const serviceType = String(value.serviceType ?? "") as SketchServiceType;
  if (!SERVICE_TYPES.has(serviceType)) {
    throw new Error(`Node ${index + 1} has an unsupported Azure service.`);
  }
  const name = String(value.name ?? "").trim();
  const region = String(value.region ?? "uksouth")
    .trim()
    .toLowerCase()
    .replaceAll(" ", "");
  if (!name) {
    throw new Error(`Node ${index + 1} requires a resource name.`);
  }
  return {
    id: cleanId(String(value.id ?? `node-${index + 1}`)),
    serviceType,
    name,
    region,
    x: finiteNumber(value.x, 80),
    y: finiteNumber(value.y, 80),
    parameters: normalizeParameters(value.parameters),
  };
}

function normalizeParameters(
  input: unknown,
): Record<string, SketchParameterValue> | undefined {
  if (!input || typeof input !== "object" || Array.isArray(input)) {
    return undefined;
  }
  const result: Record<string, SketchParameterValue> = {};
  for (const [key, value] of Object.entries(input)) {
    const normalized = normalizeParameterValue(value);
    if (normalized !== undefined) result[key] = normalized;
  }
  return Object.keys(result).length > 0 ? result : undefined;
}

function normalizeParameterValue(
  value: unknown,
): SketchParameterValue | undefined {
  if (
    typeof value === "string" ||
    typeof value === "boolean" ||
    (typeof value === "number" && Number.isFinite(value))
  ) {
    return value;
  }
  if (Array.isArray(value)) {
    return value
      .map(normalizeParameterValue)
      .filter((item): item is SketchParameterValue => item !== undefined);
  }
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value)
        .map(([key, item]) => [key, normalizeParameterValue(item)] as const)
        .filter(
          (entry): entry is readonly [string, SketchParameterValue] =>
            entry[1] !== undefined,
        ),
    );
  }
  return undefined;
}

function createContext(sketch: InfraSketch): {
  labels: Map<string, string>;
  resourceGroup?: SketchNode;
} {
  const labels = new Map<string, string>();
  const used = new Set<string>();
  for (const node of sketch.nodes) {
    const base = terraformLabel(node.name || node.serviceType);
    let label = base;
    let suffix = 2;
    while (used.has(label)) {
      label = `${base}_${suffix++}`;
    }
    used.add(label);
    labels.set(node.id, label);
  }
  return {
    labels,
    resourceGroup: sketch.nodes.find(
      (node) => node.serviceType === "resource_group",
    ),
  };
}

function renderNode(
  node: SketchNode,
  sketch: InfraSketch,
  context: ReturnType<typeof createContext>,
): string {
  const label = context.labels.get(node.id) as string;
  const rgReference = context.resourceGroup
    ? `azurerm_resource_group.${context.labels.get(context.resourceGroup.id)}.name`
    : "azurerm_resource_group.sketch.name";
  const locationReference = context.resourceGroup
    ? `azurerm_resource_group.${context.labels.get(context.resourceGroup.id)}.location`
    : "azurerm_resource_group.sketch.location";
  const dependsOn = renderDependsOn(node, sketch, context.labels);
  const tags = `  tags = {\n    managed_by = "terraform"\n    source     = "cloud-canvas"\n  }`;

  switch (node.serviceType) {
    case "resource_group":
      return block("azurerm_resource_group", label, [
        `  name     = ${JSON.stringify(node.name)}`,
        `  location = ${JSON.stringify(node.region)}`,
        tags,
        dependsOn,
      ]);
    case "virtual_network":
      return block("azurerm_virtual_network", label, [
        `  name                = ${JSON.stringify(node.name)}`,
        `  location            = ${locationReference}`,
        `  resource_group_name = ${rgReference}`,
        `  address_space       = [${JSON.stringify(parameterString(node, "addressSpace", "10.0.0.0/16"))}]`,
        tags,
        dependsOn,
      ]);
    case "subnet": {
      const vnet = connectedNode(node, sketch, "virtual_network") ??
        sketch.nodes.find((candidate) => candidate.serviceType === "virtual_network");
      if (!vnet) {
        return commentOnly(node, "Add and connect a Virtual Network before generating this subnet.");
      }
      return block("azurerm_subnet", label, [
        `  name                 = ${JSON.stringify(node.name)}`,
        `  resource_group_name  = ${rgReference}`,
        `  virtual_network_name = azurerm_virtual_network.${context.labels.get(vnet.id)}.name`,
        `  address_prefixes     = [${JSON.stringify(parameterString(node, "addressPrefix", "10.0.1.0/24"))}]`,
        dependsOn,
      ]);
    }
    case "network_security_group":
      return block("azurerm_network_security_group", label, [
        `  name                = ${JSON.stringify(node.name)}`,
        `  location            = ${locationReference}`,
        `  resource_group_name = ${rgReference}`,
        tags,
        dependsOn,
      ]);
    case "storage_account":
      return block("azurerm_storage_account", label, [
        `  name                            = ${JSON.stringify(storageName(node.name))}`,
        `  location                        = ${locationReference}`,
        `  resource_group_name             = ${rgReference}`,
        `  account_tier                    = ${JSON.stringify(parameterString(node, "accountTier", "Standard"))}`,
        `  account_replication_type        = ${JSON.stringify(parameterString(node, "replicationType", "LRS"))}`,
        `  public_network_access_enabled   = ${parameterBoolean(node, "publicNetworkAccess", false)}`,
        `  shared_access_key_enabled       = ${parameterBoolean(node, "sharedAccessKey", false)}`,
        `  min_tls_version                 = ${JSON.stringify(parameterString(node, "minimumTlsVersion", "TLS1_2"))}`,
        `  allow_nested_items_to_be_public = ${parameterBoolean(node, "allowBlobPublicAccess", false)}`,
        tags,
        dependsOn,
      ]);
    case "key_vault":
      return block("azurerm_key_vault", label, [
        `  name                       = ${JSON.stringify(truncateName(node.name, 24))}`,
        `  location                   = ${locationReference}`,
        `  resource_group_name        = ${rgReference}`,
        "  tenant_id                  = data.azurerm_client_config.current.tenant_id",
        `  sku_name                   = ${JSON.stringify(parameterString(node, "skuName", "standard"))}`,
        `  enable_rbac_authorization  = ${parameterBoolean(node, "rbacAuthorization", true)}`,
        `  public_network_access_enabled = ${parameterBoolean(node, "publicNetworkAccess", false)}`,
        `  purge_protection_enabled   = ${parameterBoolean(node, "purgeProtection", true)}`,
        tags,
        dependsOn,
      ]);
    case "service_plan":
      return block("azurerm_service_plan", label, [
        `  name                = ${JSON.stringify(node.name)}`,
        `  location            = ${locationReference}`,
        `  resource_group_name = ${rgReference}`,
        `  os_type             = ${JSON.stringify(parameterString(node, "osType", "Linux"))}`,
        `  sku_name            = ${JSON.stringify(parameterString(node, "skuName", "P1v3"))}`,
        tags,
        dependsOn,
      ]);
    case "web_app": {
      const plan = connectedNode(node, sketch, "service_plan") ??
        sketch.nodes.find((candidate) => candidate.serviceType === "service_plan");
      if (!plan) {
        return commentOnly(node, "Add and connect an App Service Plan before generating this web app.");
      }
      return block("azurerm_linux_web_app", label, [
        `  name                = ${JSON.stringify(node.name)}`,
        `  location            = ${locationReference}`,
        `  resource_group_name = ${rgReference}`,
        `  service_plan_id     = azurerm_service_plan.${context.labels.get(plan.id)}.id`,
        `  https_only          = ${parameterBoolean(node, "httpsOnly", true)}`,
        `  public_network_access_enabled = ${parameterBoolean(node, "publicNetworkAccess", false)}`,
        "",
        "  identity {",
        '    type = "SystemAssigned"',
        "  }",
        "",
        "  site_config {}",
        tags,
        dependsOn,
      ]);
    }
    case "kubernetes_service": {
      const subnet = connectedNode(node, sketch, "subnet");
      return block("azurerm_kubernetes_cluster", label, [
        `  name                = ${JSON.stringify(node.name)}`,
        `  location            = ${locationReference}`,
        `  resource_group_name = ${rgReference}`,
        `  dns_prefix          = ${JSON.stringify(truncateName(parameterString(node, "dnsPrefix", node.name) || node.name, 40))}`,
        `  private_cluster_enabled = ${parameterBoolean(node, "privateCluster", true)}`,
        `  local_account_disabled = ${parameterBoolean(node, "localAccountsDisabled", true)}`,
        `  azure_policy_enabled = ${parameterBoolean(node, "azurePolicy", true)}`,
        `  oidc_issuer_enabled = ${parameterBoolean(node, "oidcIssuer", true)}`,
        `  workload_identity_enabled = ${parameterBoolean(node, "workloadIdentity", true)}`,
        "  default_node_pool {",
        '    name       = "system"',
        `    node_count = ${parameterNumber(node, "nodeCount", 3)}`,
        `    vm_size    = ${JSON.stringify(parameterString(node, "vmSize", "Standard_D4s_v5"))}`,
        ...(subnet
          ? [
              `    vnet_subnet_id = azurerm_subnet.${context.labels.get(subnet.id)}.id`,
            ]
          : []),
        "  }",
        '  identity { type = "SystemAssigned" }',
        tags,
        dependsOn,
      ]);
    }
    case "kubernetes_namespace": {
      const cluster =
        connectedNode(node, sketch, "kubernetes_service") ??
        sketch.nodes.find(
          (candidate) => candidate.serviceType === "kubernetes_service",
        );
      if (!cluster) {
        return commentOnly(
          node,
          "Add and connect an AKS cluster before generating this namespace.",
        );
      }
      return block("kubernetes_namespace", label, [
        "  metadata {",
        `    name = ${JSON.stringify(kubernetesName(node.name))}`,
        "    labels = {",
        `      "app.kubernetes.io/managed-by" = ${JSON.stringify(parameterString(node, "managedBy", "terraform"))}`,
        `      "azure-iac-guardrail/pattern"  = ${JSON.stringify(parameterString(node, "tenancyPattern", "shared-cluster"))}`,
        "    }",
        "  }",
        `  depends_on = [azurerm_kubernetes_cluster.${context.labels.get(cluster.id)}]`,
      ]);
    }
    case "sql_server":
      return block("azurerm_mssql_server", label, [
        `  name                          = ${JSON.stringify(node.name)}`,
        `  location                      = ${locationReference}`,
        `  resource_group_name           = ${rgReference}`,
        `  version                       = ${JSON.stringify(parameterString(node, "version", "12.0"))}`,
        `  public_network_access_enabled = ${parameterBoolean(node, "publicNetworkAccess", false)}`,
        `  minimum_tls_version           = ${JSON.stringify(parameterString(node, "minimumTlsVersion", "1.2"))}`,
        "  azuread_administrator {",
        `    login_username = ${JSON.stringify(parameterString(node, "administratorLogin", "current-terraform-principal"))}`,
        "    object_id      = data.azurerm_client_config.current.object_id",
        "  }",
        tags,
        dependsOn,
      ]);
    case "sql_database": {
      const server = connectedNode(node, sketch, "sql_server") ??
        sketch.nodes.find((candidate) => candidate.serviceType === "sql_server");
      if (!server) {
        return commentOnly(node, "Add and connect a SQL Server before generating this database.");
      }
      return block("azurerm_mssql_database", label, [
        `  name      = ${JSON.stringify(node.name)}`,
        `  server_id = azurerm_mssql_server.${context.labels.get(server.id)}.id`,
        `  sku_name  = ${JSON.stringify(parameterString(node, "skuName", "S0"))}`,
        `  zone_redundant = ${parameterBoolean(node, "zoneRedundant", false)}`,
        tags,
        dependsOn,
      ]);
    }
    case "container_registry":
      return block("azurerm_container_registry", label, [
        `  name                          = ${JSON.stringify(alphaNumeric(node.name))}`,
        `  location                      = ${locationReference}`,
        `  resource_group_name           = ${rgReference}`,
        `  sku                           = ${JSON.stringify(parameterString(node, "sku", "Premium"))}`,
        `  admin_enabled                 = ${parameterBoolean(node, "adminEnabled", false)}`,
        `  public_network_access_enabled = ${parameterBoolean(node, "publicNetworkAccess", false)}`,
        tags,
        dependsOn,
      ]);
    case "event_hubs":
      return [
        block("azurerm_eventhub_namespace", label, [
          `  name                          = ${JSON.stringify(node.name)}`,
          `  location                      = ${locationReference}`,
          `  resource_group_name           = ${rgReference}`,
          `  sku                           = ${JSON.stringify(parameterString(node, "sku", "Standard"))}`,
          `  capacity                      = ${parameterNumber(node, "capacity", 1)}`,
          `  public_network_access_enabled = ${parameterBoolean(node, "publicNetworkAccess", false)}`,
          `  local_authentication_enabled  = ${parameterBoolean(node, "localAuthentication", false)}`,
          tags,
          dependsOn,
        ]),
        block("azurerm_eventhub", `${label}_events`, [
          `  name              = ${JSON.stringify(parameterString(node, "eventHubName", "events"))}`,
          `  namespace_id      = azurerm_eventhub_namespace.${label}.id`,
          `  partition_count   = ${parameterNumber(node, "partitionCount", 4)}`,
          `  message_retention = ${parameterNumber(node, "messageRetention", 1)}`,
        ]),
      ].join("");
    case "event_grid":
      return block("azurerm_eventgrid_topic", label, [
        `  name                          = ${JSON.stringify(node.name)}`,
        `  location                      = ${locationReference}`,
        `  resource_group_name           = ${rgReference}`,
        `  input_schema                  = ${JSON.stringify(parameterString(node, "inputSchema", "EventGridSchema"))}`,
        `  public_network_access_enabled = ${parameterBoolean(node, "publicNetworkAccess", false)}`,
        `  local_auth_enabled            = ${parameterBoolean(node, "localAuthentication", false)}`,
        tags,
        dependsOn,
      ]);
    case "service_bus":
      return [
        block("azurerm_servicebus_namespace", label, [
          `  name                          = ${JSON.stringify(node.name)}`,
          `  location                      = ${locationReference}`,
          `  resource_group_name           = ${rgReference}`,
          `  sku                           = ${JSON.stringify(parameterString(node, "sku", "Premium"))}`,
          `  capacity                      = ${parameterNumber(node, "capacity", 1)}`,
          `  public_network_access_enabled = ${parameterBoolean(node, "publicNetworkAccess", false)}`,
          `  local_auth_enabled            = ${parameterBoolean(node, "localAuthentication", false)}`,
          tags,
          dependsOn,
        ]),
        block("azurerm_servicebus_queue", `${label}_messages`, [
          `  name         = ${JSON.stringify(parameterString(node, "queueName", "messages"))}`,
          `  namespace_id = azurerm_servicebus_namespace.${label}.id`,
          `  enable_partitioning = ${parameterBoolean(node, "partitioning", true)}`,
          `  max_size_in_megabytes = ${parameterNumber(node, "maxSizeMegabytes", 1024)}`,
        ]),
      ].join("");
    case "log_analytics":
      return block("azurerm_log_analytics_workspace", label, [
        `  name                = ${JSON.stringify(node.name)}`,
        `  location            = ${locationReference}`,
        `  resource_group_name = ${rgReference}`,
        `  sku                 = ${JSON.stringify(parameterString(node, "sku", "PerGB2018"))}`,
        `  retention_in_days   = ${parameterNumber(node, "retentionDays", 30)}`,
        tags,
        dependsOn,
      ]);
    default: {
      const mapped = mappedService(node.serviceType);
      if (mapped?.terraform.resourceType) {
        return genericTerraformBlock(
          node,
          mapped,
          label,
          rgReference,
          locationReference,
          dependsOn,
        );
      }
      return commentOnly(
        node,
        "This service is included in the architecture diagram but does not yet have a generated Terraform template.",
      );
    }
  }
}

interface MappedService {
  terraform: {
    resourceType: string | null;
    automaticArguments: string[];
    parameters: Array<{
      key: string;
      required: boolean;
      nestedBlock: boolean;
      defaultValue: unknown;
    }>;
  };
}

function mappedService(serviceType: string): MappedService | undefined {
  return (
    completeCatalog.services as unknown as Record<string, MappedService>
  )[serviceType];
}

function genericTerraformBlock(
  node: SketchNode,
  mapped: MappedService,
  label: string,
  resourceGroupReference: string,
  locationReference: string,
  dependsOn: string,
): string {
  if (!mapped.terraform.resourceType) {
    return commentOnly(node, "No Terraform resource type is mapped.");
  }
  const lines: string[] = [];
  if (mapped.terraform.automaticArguments.includes("name")) {
    lines.push(`  name = ${JSON.stringify(node.name)}`);
  }
  if (mapped.terraform.automaticArguments.includes("location")) {
    lines.push(`  location = ${locationReference}`);
  }
  if (mapped.terraform.automaticArguments.includes("resource_group_name")) {
    lines.push(`  resource_group_name = ${resourceGroupReference}`);
  }
  for (const definition of mapped.terraform.parameters) {
    const value = node.parameters?.[definition.key] ?? definition.defaultValue;
    if (definition.nestedBlock) {
      lines.push(
        `  # TODO: configure ${definition.required ? "required " : ""}nested block "${definition.key}".`,
      );
    } else if (value === "" || value === undefined || value === null) {
      lines.push(
        `  # TODO: ${definition.required ? "required " : ""}${definition.key} = <value>`,
      );
    } else {
      lines.push(`  ${definition.key} = ${terraformValue(value)}`);
    }
  }
  lines.push(dependsOn);
  return block(mapped.terraform.resourceType, label, lines);
}

function terraformValue(value: unknown): string {
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }
  return JSON.stringify(value);
}

function renderNetworkAssociations(
  sketch: InfraSketch,
  context: ReturnType<typeof createContext>,
): string[] {
  const rendered = new Set<string>();
  const associations: string[] = [];
  for (const connection of sketch.connections) {
    const source = sketch.nodes.find((node) => node.id === connection.source);
    const target = sketch.nodes.find((node) => node.id === connection.target);
    if (!source || !target) {
      continue;
    }
    const subnet =
      source.serviceType === "subnet"
        ? source
        : target.serviceType === "subnet"
          ? target
          : undefined;
    const networkSecurityGroup =
      source.serviceType === "network_security_group"
        ? source
        : target.serviceType === "network_security_group"
          ? target
          : undefined;
    if (!subnet || !networkSecurityGroup) {
      continue;
    }
    const associationKey = `${subnet.id}:${networkSecurityGroup.id}`;
    if (rendered.has(associationKey)) {
      continue;
    }
    rendered.add(associationKey);
    const subnetLabel = context.labels.get(subnet.id) as string;
    const networkSecurityGroupLabel = context.labels.get(
      networkSecurityGroup.id,
    ) as string;
    associations.push(
      block(
        "azurerm_subnet_network_security_group_association",
        `${subnetLabel}_${networkSecurityGroupLabel}`,
        [
          `  subnet_id                 = azurerm_subnet.${subnetLabel}.id`,
          `  network_security_group_id = azurerm_network_security_group.${networkSecurityGroupLabel}.id`,
        ],
      ),
    );
  }
  return associations;
}

function renderDependsOn(
  node: SketchNode,
  sketch: InfraSketch,
  labels: Map<string, string>,
): string {
  const dependencies = sketch.connections
    .filter(
      (connection) =>
        connection.source === node.id ||
        (connection.bidirectional === true && connection.target === node.id),
    )
    .map((connection) =>
      sketch.nodes.find((item) =>
        connection.source === node.id
          ? item.id === connection.target
          : item.id === connection.source,
      ),
    )
    .filter((item): item is SketchNode => item !== undefined)
    .map((item) => terraformAddress(item, labels.get(item.id) as string))
    .filter((address): address is string => address !== undefined);
  return dependencies.length > 0
    ? `  depends_on = [${[...new Set(dependencies)].join(", ")}]`
    : "";
}

function connectedNode(
  node: SketchNode,
  sketch: InfraSketch,
  serviceType: SketchServiceType,
): SketchNode | undefined {
  const connectedIds = sketch.connections.flatMap((connection) =>
    connection.source === node.id
      ? [connection.target]
      : connection.target === node.id
        ? [connection.source]
        : [],
  );
  return sketch.nodes.find(
    (candidate) =>
      connectedIds.includes(candidate.id) &&
      candidate.serviceType === serviceType,
  );
}

function terraformAddress(
  node: SketchNode,
  label: string,
): string | undefined {
  const type: Record<string, string> = {
    resource_group: "azurerm_resource_group",
    virtual_network: "azurerm_virtual_network",
    subnet: "azurerm_subnet",
    network_security_group: "azurerm_network_security_group",
    storage_account: "azurerm_storage_account",
    key_vault: "azurerm_key_vault",
    service_plan: "azurerm_service_plan",
    web_app: "azurerm_linux_web_app",
    kubernetes_service: "azurerm_kubernetes_cluster",
    kubernetes_namespace: "kubernetes_namespace",
    sql_server: "azurerm_mssql_server",
    sql_database: "azurerm_mssql_database",
    container_registry: "azurerm_container_registry",
    log_analytics: "azurerm_log_analytics_workspace",
    event_hubs: "azurerm_eventhub_namespace",
    event_grid: "azurerm_eventgrid_topic",
    service_bus: "azurerm_servicebus_namespace",
  };
  const resourceType = type[node.serviceType];
  return resourceType ? `${resourceType}.${label}` : undefined;
}

function block(type: string, label: string, lines: string[]): string {
  return [
    `resource "${type}" "${label}" {`,
    ...lines.filter((line) => line !== ""),
    "}",
    "",
  ].join("\n");
}

function commentOnly(node: SketchNode, message: string): string {
  return [
    `# ${node.name} (${node.serviceType}) was not generated.`,
    `# ${message}`,
    "",
  ].join("\n");
}

function terraformLabel(value: string): string {
  const result = value
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return /^[a-z_]/.test(result) ? result || "resource" : `resource_${result}`;
}

function storageName(value: string): string {
  return truncateName(alphaNumeric(value).toLowerCase(), 24).padEnd(3, "0");
}

function alphaNumeric(value: string): string {
  return value.replace(/[^a-zA-Z0-9]/g, "");
}

function truncateName(value: string, length: number): string {
  return value.slice(0, length);
}

function parameterString(
  node: SketchNode,
  key: string,
  fallback: string,
): string {
  const value = node.parameters?.[key];
  return typeof value === "string" ? value : fallback;
}

function parameterNumber(
  node: SketchNode,
  key: string,
  fallback: number,
): number {
  const value = node.parameters?.[key];
  return typeof value === "number" && Number.isFinite(value)
    ? value
    : fallback;
}

function parameterBoolean(
  node: SketchNode,
  key: string,
  fallback: boolean,
): boolean {
  const value = node.parameters?.[key];
  return typeof value === "boolean" ? value : fallback;
}

export interface SketchParameterDefinition {
  key: string;
  label: string;
  type: "text" | "number" | "boolean" | "select" | "json";
  defaultValue: SketchParameterValue | Record<string, unknown> | unknown[];
  options?: string[];
  min?: number;
  max?: number;
  step?: number;
  required?: boolean;
  nestedBlock?: boolean;
  controlIds?: string[];
  remediation?: string;
}

export const SKETCH_PARAMETER_DEFINITIONS = Object.fromEntries(
  Object.values(completeCatalog.services).map((service) => [
    service.serviceId,
    service.terraform.parameters,
  ]),
) as Record<string, SketchParameterDefinition[]>;

function kubernetesProvider(clusterLabel: string): string[] {
  return [
    'provider "kubernetes" {',
    `  host                   = azurerm_kubernetes_cluster.${clusterLabel}.kube_config[0].host`,
    `  client_certificate     = base64decode(azurerm_kubernetes_cluster.${clusterLabel}.kube_config[0].client_certificate)`,
    `  client_key             = base64decode(azurerm_kubernetes_cluster.${clusterLabel}.kube_config[0].client_key)`,
    `  cluster_ca_certificate = base64decode(azurerm_kubernetes_cluster.${clusterLabel}.kube_config[0].cluster_ca_certificate)`,
    "}",
    "",
  ];
}

function kubernetesName(value: string): string {
  const result = value
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 63);
  return result || "namespace";
}

function cleanId(value: string): string {
  const result = value.replace(/[^a-zA-Z0-9_-]/g, "");
  if (!result) {
    throw new Error("Sketch IDs must contain letters or numbers.");
  }
  return result;
}

function finiteNumber(value: unknown, fallback: number): number {
  return typeof value === "number" && Number.isFinite(value)
    ? value
    : fallback;
}
